[phases.setup]
nixPkgs = ['nodejs_18', 'ffmpeg', 'yt-dlp']

[phases.install]
cmds = ['cd backend && npm ci']

[start]
cmd = 'cd backend && node server.js'

[variables]
NO_CACHE = '1'
NODE_ENV = 'production' 