[phases.setup]
nixPkgs = ["nodejs_18", "ffmpeg", "yt-dlp"]

[phases.install]
cmds = ["npm install", "cd backend && npm install --only=production"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3000" 