[phases.setup]
nixPkgs = ["nodejs_18", "ffmpeg", "yt-dlp"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production" 