[phases.setup]
nixPkgs = ["nodejs_18", "ffmpeg", "yt-dlp"]

[phases.install]
cmds = ["npm install", "cd backend && npm ci --only=production"]

[start]
cmd = "node start.js"

[variables]
NODE_ENV = 'production' 