[phases.setup]
nixPkgs = ["nodejs_18", "ffmpeg", "yt-dlp"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'Build completed successfully'"]

[start]
cmd = "node app/index.js"

[variables]
NODE_ENV = "production"
PORT = "3000" 