[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm ci"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

[env]
NO_CACHE = "1"
NODE_ENV = "production" 