[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production]
PORT = 3000

[env]
NODE_ENV = "production" 