services:
  - type: web
    name: music-downloader
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node app/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: music-downloader
          property: port 